spring.application.name=riayati-middleware
# Server Settings
server.port=8066

# DHPO Integration Credentials & Endpoints
dhpo.client.endpoint=https://dhpo.eclaimlink.ae/ValidateTransactions.asmx
dhpo.client.default-uri=http://www.eClaimLink.ae/
dhpo.client.username=YOUR_LOGIN_ID
dhpo.client.password=YOUR_PASSWORD

# mTLS Security Settings
dhpo.security.key-store=classpath:keystore/dhpo-client.p12
dhpo.security.key-store-password=YOUR_CERT_PASSWORD
dhpo.security.key-store-type=PKCS12
