package com.ntigra.riayati_middleware.dto.request.erx.request;

import lombok.Data;
import java.util.List;

@Data
public class ErxPrescription {
    private String id;
    private String type;                  // eRxRequest or eRxCancellation
    private String referenceNumber;       // Auto-generated by TMB
    private String clinician;
    private ErxPatient patient;
    private ErxEncounter encounter;
    private List<ErxDiagnosis> diagnosis;
    private List<ErxActivity> activity;
}
