package com.ntigra.riayati_middleware.dto.entity.ERX;

import com.ntigra.riayati_middleware.dto.entity.Diagnosis;
import com.ntigra.riayati_middleware.dto.entity.Encounter;
import lombok.Builder;
import lombok.Data;
import java.util.List;

@Data
@Builder
public class ErxPrescription {
    private String id;                      // PreAuthRef
    private String type;                    // "eRxRequest" or "eRxCancellation"
    private String referenceNumber;         // Auto-generated by TMB (response)
    private String clinician;               // Constant
    private ErxPatient patient;
    private Encounter encounter;
    private List<Diagnosis> diagnosis;
    private List<ErxPrescriptionActivity> activity;
}