package com.ntigra.riayati_middleware.dto.entity.ERX;

import lombok.Data;
import java.time.LocalDateTime;

@Data
public class ErxRequest {
    private Long id;
    private String prescriptionId;
    private String referenceNumber;      // Generated by Riayati TMB
    private String entityId;              // Riayati's transaction ID
    private String clinician;             // Clinician license
    private String transactionType;       // eRxRequest or eRxCancellation

    // Patient Information
    private String memberId;
    private String emiratesId;
    private String patientName;
    private String gender;
    private String dateOfBirth;
    private String contactNumber;
    private String email;
    private Double weight;

    // Encounter Information
    private String facilityId;
    private Integer encounterType;
    private String encounterStart;
    private String encounterEnd;

    // Status Tracking
    private String status;                // PENDING, SENT, FAILED, RETRY, PROCESSED
    private Integer retryCount;
    private String errorMessage;

    // Response Fields (from Payer)
    private String result;                // Yes/No
    private String idPayer;
    private String denialCode;
    private String startDate;
    private String endDate;
    private Double coverageLimit;
    private String responseData;          // Full JSON response

    // Timestamps
    private LocalDateTime createdAt;
    private LocalDateTime sentAt;
    private LocalDateTime processedAt;
}
